name: Build & Push Docker image to DockerHub

on:
  push:
    branches:
      - main

env:
  IMAGE_NAME: monokkay/training-service

jobs:
  docker:
    runs-on: ubuntu-latest

    steps:
      - name: ðŸ”„ Checkout repository
        uses: actions/checkout@v3

      - name: ðŸ³ Log in to DockerHub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: ðŸ—ï¸ Build and tag image
        run: |
          GIT_SHORT_SHA=$(git rev-parse --short HEAD)
          echo "GIT_SHORT_SHA=$GIT_SHORT_SHA" >> $GITHUB_ENV
          docker build -t $IMAGE_NAME:$GIT_SHORT_SHA -t $IMAGE_NAME:latest .

      - name: ðŸ“¤ Push image to DockerHub
        run: |
          docker push $IMAGE_NAME:$GIT_SHORT_SHA
          docker push $IMAGE_NAME:latest
